print ("Saisir le jour du mois :")
jour = input()
print ("Saisir lheure de la journée :")
heure = int(input())
print ("Saisir les minutes :")
minute = int(input())
jour = int(jour)
tot = ((jour-1)*24*60 + heure*60 + minute)
print (f"Le nombre total de minutes depuis le début du mois est {tot}")
